services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - "54327:5432"
    environment:
      - POSTGRES_PASSWORD=tk@061247
      - POSTGRES_USER=thanakrit
      - POSTGRES_DB=thanakrit
    volumes:
      - ./data/data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4:latest
    container_name: 69-s1-admin
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=thanakrit@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=tk@061247
    depends_on:
      - db
